### ISSUE TITLE
can't load the project 

### ISSUE THREAD

**Issue by hamaln** [thenineteen/Semiology-Visualisation-Tool#236]
can't load the projects into the program and this is the message I got: 

Python 3.9.10 (main, Jan 19 2023, 00:06:32) [MSC v.1930 64 bit (AMD64)] on win32
>>> 
Loading Slicer RC file [C:/Users/tiger/.slicerrc.py]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'C:UserstigerDesktopSemiology-Visualisation-Tool-masterSemiology-Visualisation-Tool-masterrequirements.txt'

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python-real.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:/Users/tiger/Desktop/Semiology-Visualisation-Tool-master/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualisation.py", line 1423, in installRepository
    import mega_analysis
  File "C:\Users\tiger\Desktop\Semiology-Visualisation-Tool-master\Semiology-Visualisation-Tool-master\mega_analysis\__init__.py", line 2, in <module>
    from .crosstab.gif_lobes_from_excel_sheets import gif_lobes_from_excel_sheets
  File "C:\Users\tiger\Desktop\Semiology-Visualisation-Tool-master\Semiology-Visualisation-Tool-master\mega_analysis\crosstab\gif_lobes_from_excel_sheets.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tiger/Desktop/Semiology-Visualisation-Tool-master/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualisation.py", line 99, in setup
    self.logic.installRepository()
  File "C:/Users/tiger/Desktop/Semiology-Visualisation-Tool-master/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualisation.py", line 1429, in installRepository
    slicer.util.pip_install(
  File "C:\Users\tiger\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-16\bin\Python\slicer\util.py", line 3586, in pip_install
    _executePythonModule('pip', args)
  File "C:\Users\tiger\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-16\bin\Python\slicer\util.py", line 3548, in _executePythonModule
    logProcessOutput(proc)
  File "C:\Users\tiger\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-16\bin\Python\slicer\util.py", line 3517, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/tiger/AppData/Local/NA-MIC/Slicer 5.3.0-2023-01-16/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', '-r', 'C:UserstigerDesktopSemiology-Visualisation-Tool-masterSemiology-Visualisation-Tool-masterrequirements.txt']' returned non-zero exit status 1.

**Comment by KrishU27** [comment]
Same issue here too

**Comment by gauerlucas** [comment]
Same issue with Slicer 5.5.0, I've been able to go around the problem after two steps :

1. _(maybe this step is not useful if step 2 and 3 are done before)_ : Hard-coding the path of the requirements file in line 1425 of SemiologyVisualisation.py, in my case :
`requirementsPath = 'D:/0_softwares/Semiology-Visualisation-Tool-master/requirements.txt`
Only doing this was throwing another error saying that pandas module was not found. So I carried on with the following :
2. Uninstall requirements in the Slicer Python console using :
`slicer.util.pip_uninstall("matplotlib matplotlib_venn pandas PyYAML seaborn scikit-learn xlrd tqdm colorama openpyxl numpy==1.19.5")`
3. Manually reinstall requirements using :
`slicer.util.pip_install("matplotlib matplotlib_venn pandas PyYAML seaborn scikit-learn xlrd tqdm colorama openpyxl numpy==1.19.5")`
4. launch SVT

Works well after that ! :)

**Comment by chinmaychinara91** [comment]
Followed the steps suggested by @gauerlucas but get the following error when running `slicer.util.pip_install("numpy==1.19.5")`. Any suggestions ?

```
Collecting numpy==1.19.5
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\cli\req_command.py", line 68, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\commands\install.py", line 387, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 96, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 515, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 388, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 141, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 194, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 163, in __bool__
    self._bool = any(self)
                 ^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 147, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 37, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__
    super().__init__(
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\operations\prepare.py", line 532, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\operations\prepare.py", line 647, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_internal\utils\misc.py", line 702, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\lib\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\bin\Python\slicer\util.py", line 4034, in pip_install
    _executePythonModule("pip", args)
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\bin\Python\slicer\util.py", line 3988, in _executePythonModule
    logProcessOutput(proc)
  File "C:\Users\chinm\AppData\Local\slicer.org\Slicer 5.9.0-2025-09-15\bin\Python\slicer\util.py", line 3954, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/chinm/AppData/Local/slicer.org/Slicer 5.9.0-2025-09-15/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'numpy==1.19.5']' returned non-zero exit status 2.```
