### ISSUE TITLE
ModuleNotFoundError and subprocess.CalledProcessError in Slicer module

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#25]
When I open 3D slicer and run the Semiology Visualisation, (after I've updated the module path folder) I still get the izma error plus now all these:

```python-traceback
Traceback (most recent call last):
  File "C:/Users/ali_m/AnacondaProjects/PhD/Semiology-Visualisation-Tool/slicer/SemiologyVisualization.py", line 416, in installRepository
    import mega_analysis
  File "C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\mega_analysis\__init__.py", line 4, in <module>
    from .scores import get_scores_dict, get_all_semiology_terms
  File "C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\mega_analysis\scores.py", line 7, in <module>
    from mega_analysis.crosstab.mega_analysis.MEGA_ANALYSIS import MEGA_ANALYSIS
  File "C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\mega_analysis\crosstab\mega_analysis\MEGA_ANALYSIS.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\site-packages\matplotlib\pyplot.py", line 2282, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\site-packages\matplotlib\pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\site-packages\matplotlib\backends\backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\site-packages\matplotlib\backends\_backend_tk.py", line 6, in <module>
    import tkinter as tk
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\tkinter\__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ali_m/AnacondaProjects/PhD/Semiology-Visualisation-Tool/slicer/SemiologyVisualization.py", line 47, in setup
    self.logic.installRepository()
  File "C:/Users/ali_m/AnacondaProjects/PhD/Semiology-Visualisation-Tool/slicer/SemiologyVisualization.py", line 420, in installRepository
    f'-r {requirementsPath}'
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\bin\Python\slicer\util.py", line 2142, in pip_install
    logProcessOutput(proc)
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\bin\Python\slicer\util.py", line 2095, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/ali_m/AppData/Local/NA-MIC/Slicer 4.11.0-2020-03-24/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', '-r', 'C:\\Users\\ali_m\\AnacondaProjects\\PhD\\Semiology-Visualisation-Tool\\requirements.txt']' returned non-zero exit status 1.
```

**Comment by fepegar** [comment]
1. The `lzma` issue is just a warning, I don't think it's relevant to us.
1. `ModuleNotFoundError`: I thought I solved this with these lines https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/b10801202815cddb877b5a989d48b078fa37a59e/slicer/SemiologyVisualization.py#L422-L423
Is the clone up to date?
1. `subprocess.CalledProcessError`: Slicer uses the `pip` module to pip-install the libraries in `requirements.txt`. I don't know why this error happens, the message is not very informative either. I'll try the module on Windows and see if I get the same. Maybe you can try calling this from a terminal and see what happens:
```
C:/Users/ali_m/AppData/Local/NA-MIC/Slicer 4.11.0-2020-03-24/bin/../bin\\PythonSlicer.EXE -m pip install -r C:\\Users\\ali_m\\AnacondaProjects\\PhD\\Semiology-Visualisation-Tool\\requirements.txt
```

**Comment by fepegar** [comment]
I don't get the `tkinter` error in Slicer if I set the backend to `agg`:

```python
>>> import matplotlib
>>> matplotlib.use('agg')
>>> import matplotlib.pyplot as plt
>>> plt.show()
```

**Comment by thenineteen** [comment]
line 422 of SemiologyVisualization.py sets the backend to 'agg' and I have this up to date locally (I've used git pull rather than clone but shouldn't make a difference?).

Could it be something to do with version of python (or using a windows machine) for example, can't think of anything else

**Comment by fepegar** [comment]
Yes, git pull should be fine. I'll try Windows today.

**Comment by fepegar** [comment]
I'm getting this error when opening the module in Slicer, while it tries to install the requirements. The process stops because PIP can't fin `re` in PyPI. Makes sense as `re` is a native Python module.

```python-traceback
Collecting pandas
  Downloading pandas-1.0.3-cp36-cp36m-win_amd64.whl (8.7 MB)
Collecting PyYaml
  Downloading PyYAML-5.3.1-cp36-cp36m-win_amd64.whl (215 kB)
ERROR: Could not find a version that satisfies the requirement re (from -r C:\Users\fernando\git\Semiology-Visualisation-Tool\requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for re (from -r C:\Users\fernando\git\Semiology-Visualisation-Tool\requirements.txt (line 3))
```

**Comment by fepegar** [comment]
I fixed the requirements. Can you try again?

**Comment by thenineteen** [comment]
excellent
