### ISSUE TITLE
UnicodeDecodeError when trying to read semiologies dictionary

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#29]
Reported by @neurokleos.

```python-traceback
/Users/romagnog/Desktop/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pandas/compat/_init_.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/Users/romagnog/Desktop/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualization.py", line 52, in setup
    self.makeGUI()
  File "/Users/romagnog/Desktop/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualization.py", line 60, in makeGUI
    self.makeSemiologiesButton()
  File "/Users/romagnog/Desktop/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualization.py", line 134, in makeSemiologiesButton
    semiologiesFormLayout.addWidget(self.getSemiologiesWidget())
  File "/Users/romagnog/Desktop/Semiology-Visualisation-Tool-master/slicer/SemiologyVisualization.py", line 171, in getSemiologiesWidget
    get_all_semiology_terms(), self.onAutoUpdateButton)
  File "/Users/romagnog/Desktop/Semiology-Visualisation-Tool-master/mega_analysis/scores.py", line 54, in get_all_semiology_terms
    dictionary = yaml.load(f, Loader=yaml.FullLoader)
  File "/Users/romagnog/Desktop/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/yaml/_init_.py", line 112, in load
    loader = Loader(stream)
  File "/Users/romagnog/Desktop/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/yaml/loader.py", line 24, in _init_
    Reader._init_(self, stream)
  File "/Users/romagnog/Desktop/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/yaml/reader.py", line 85, in _init_
    self.determine_encoding()
  File "/Users/romagnog/Desktop/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/Users/romagnog/Desktop/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/Users/romagnog/Desktop/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2585: ordinal not in range(128)
could not find nodes in the scene by name or id 'MNI_152_gif'
Segmentation not found in scene: MNI_152_gif_cerebrum
```

**Comment by fepegar** [comment]
It looks like this error is caused by special characters in the [semiology dictionary YAML file](https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/resources/semiology_dictionary.yaml), probably those in *déjà vu*.

**Comment by fepegar** [comment]
See https://stackoverflow.com/q/24475393/3956024
