### ISSUE TITLE
Return None for wrong semiologies

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#33]
I think the module should return `None` if the semiology term is wrong.

**Comment by fepegar** [comment]
@thenineteen Shall I work on this?

**Comment by thenineteen** [comment]
There is no "wrong" semiology term. It may not be found - but if that is the case, I need to check it is working correctly. If it is working correctly, it is best we remove that semiology checkbox altogether.

- I think partly it does this currently by showing nothing. 

- The other part is the confusion with using lateraliation (e.g. R or L) when there is none e.g. Aphasia see #34 which may help

- most importantly, we need a free text box which uses the modules regex - this will allow user flexibility and searching for all sorts of semiologies which aren't captured in the semiology_dictionary

**Comment by fepegar** [comment]
Let's ignore the GUI for a second. If I enter `'Test'` as semiology term, do you agree that the function should return `None`? Then we can choose a message to be displayed.

**Comment by thenineteen** [comment]
I'm being overly scrupulous, but if "test" is found in the context of someone having seizure during exams, then this may occur in the excel and will be picked up... but yes if you write "asdfg" then it already gives you an error message:

'QUERY SEMIOLOGY ERROR: This semiology was not found within the reported literature nor in the semiology categories'

**Comment by fepegar** [comment]
I'm not getting that error:
```python-traceback
Scores dictionary for semiology term dsf not retrieved:
'Lateralising'
Traceback (most recent call last):
  File "/Users/fernando/miniconda3/envs/ali/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4736, in get_value
    return libindex.get_value_box(s, key)
  File "pandas/_libs/index.pyx", line 51, in pandas._libs.index.get_value_box
  File "pandas/_libs/index.pyx", line 47, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fernando/git/Semiology-Visualisation-Tool/mega_analysis/scores.py", line 196, in get_scores_dict
    output_path=output_path,
  File "/Users/fernando/git/Semiology-Visualisation-Tool/mega_analysis/scores.py", line 151, in get_scores
    pts_dominant_hemisphere_R_or_L=dominant_hemisphere,
  File "/Users/fernando/git/Semiology-Visualisation-Tool/mega_analysis/crosstab/mega_analysis/QUERY_LATERALISATION.py", line 76, in QUERY_LATERALISATION
    print('The inspect_result has NaNs/zero where it should not: check data at row(s) ', missing_lat.loc[missing_lat['Lateralising'].isnull()].index)
  File "/Users/fernando/miniconda3/envs/ali/lib/python3.6/site-packages/pandas/core/series.py", line 1071, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/fernando/miniconda3/envs/ali/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4744, in get_value
    raise e1
  File "/Users/fernando/miniconda3/envs/ali/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4730, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 128, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 91, in pandas._libs.index.Int64Engine._check_type
KeyError: 'Lateralising'
```

I think showing a message is nice, but I think the best way to communicate Slicer the fact that the semiology is not found is by setting it to `None`.
